apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hbxhib2kz-go 
  janus-idp.io/tekton: hbxhib2kz-go
  backstage.io/kubernetes-id: hbxhib2kz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hbxhib2kz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml