apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hbxhib2kz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hbxhib2kz-go 
  name: hbxhib2kz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hbxhib2kz-go 
