apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hbxhib2kz-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-go:e684ac18427d1ce4de7ffe0ea21a745b6518ab82@sha256:3ede3e927cc50ea82424b33baa2e85ed7a46bc15df87834f9d1ef3ffaaaa87df
          name: container-image
